language: python
os: linux
sudo: required
services:
  - docker
python:
  - "2.7"
  - "3.6"
before_install:
  - pip install -U ansible ansible-lint
script:
  - ansible-lint addons.yml
  - ansible-lint cluster.yml
  - ansible-lint reset-cluster.yml
